web:
  build: .
  command: sh -c 'npm install; npm start'
  ports:
    - '4000:4000'
  volumes:
    - /home/axel/Escritorio/api_grupos_dif/api:/api
  links:
    - "db:redis"
db:
  image: redis
  ports:
    - "6379:6379"

